### ISSUE TITLE
Session file from temp(in Ubuntu XAMPP & tmp from Windows XAMPP) not deleted after logout/sess_destroy().

### ISSUE THREAD

**Issue by ganeshaher** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#62]
First of all its really wonderful experience to use this Repo. @kishor10d you really did a great job.

My issue is when I'm logged out from the system the file which is created into temp folder is not deleted, so I'm getting confused the session is destroyed or not.

Another thing is that if we create two projects on the same server and if log in into one application, another will automatically get logged in. It uses the same session file from the temp folder. It did not check the database for a user is present or not. 

The third point is for what purpose you created ci_session table in the database, as it is not used by the system.

**Comment by kishor10d** [comment]
@ganeshaher : 
1) For session file related issue, I need to check codeigniter's session management behavior.

2) You have two project, but both project sharing same encryption key. That's why the problem of logging out from both projects. Change encryption key.
Filepath : ```application/config/config.php```
You need to change this - ```$config['encryption_key'] = 'asjkrue*$djasfl134213';``` and set something else.

3) I have given ```ci_session``` table in database, just because if someone wants to store their session in database then they can easily utilize that table.
